version: '3.8'

services:
  postgres_db:
    image: postgres:15
    container_name: divine_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: divine_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: divine_server
    restart: always
    depends_on:
      - postgres_db
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: production
      PORT: 4000
      DATABASE_URL: "postgresql://user:password@postgres_db:5432/divine_db?schema=public"
      JWT_SECRET: "change_this_secret_in_production"
      JWT_ACCESS_EXPIRATION_MINUTES: 60
      JWT_REFRESH_EXPIRATION_DAYS: 30
      CLIENT_ORIGIN: "http://localhost:5173" # Update this to your frontend's production URL
    command: sh -c "npx prisma migrate deploy && npx prisma db seed && npm run start"


  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: divine_client
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - server

volumes:
  postgres_data: